name: coUserver
version: 0.0.0
author: coU Development Team
description: The sourcecode/tools needed to hack/compile the Children of Ur server
dependencies:
  intl: any
  http: any
  redstone: "^0.5.1"
  postgresql: any
  redstone_mapper_pg: "0.1.1"
  slack: any
  shelf: any
  image: any
  crypto: any
  harvest: "^2.0.0"
  jsonx: any