name: coUserver
version: 0.0.0
author: coU Development Team
description: The sourcecode/tools needed to hack/compile the Children of Ur server
dependencies:
  http_server: any
  intl: any
  slack:
    git:
      ref: master
      url: https://github.com/ChildrenOfUr/dart-slack