name: coUserver
version: 0.0.0
author: coU Development Team
description: The sourcecode/tools needed to hack/compile the Children of Ur server
dependencies:
  intl: any
  redstone: any
  postgresql: any
  redstone_mapper_pg: any
  slack: any