name: coUserver
version: 0.0.0
author: coU Development Team
description: The sourcecode/tools needed to hack/compile the Children of Ur server
dependencies:
  intl: "^0.12.6"
  http: "^0.11.3+3"
  redstone:
    git: https://github.com/redstone-dart/redstone.git
  redstone_mapper_pg:
    git: https://github.com/RobertMcDermot/redstone_mapper_pg.git
  slack: "^1.2.2"
  image: "^1.1.25"
  crypto: "^0.9.1"
  harvest: "^2.0.11"
  jsonx: "2.0.0"